# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "JOURNEYS" ("NAME" VARCHAR(254) NOT NULL,"ID" SERIAL NOT NULL PRIMARY KEY);
create table "JOURNEY_LEGS" ("JOURNEY_ID" INTEGER NOT NULL,"FROM" INTEGER NOT NULL,"TO" INTEGER NOT NULL,"ID" SERIAL NOT NULL PRIMARY KEY);
create table "PLACES" ("NAME" VARCHAR(254) NOT NULL,"LATITUDE" DOUBLE PRECISION NOT NULL,"LONGITUDE" DOUBLE PRECISION NOT NULL,"ID" SERIAL NOT NULL PRIMARY KEY);
create table "WINDS" ("ALTITUDE" INTEGER NOT NULL PRIMARY KEY,"DIR" INTEGER NOT NULL,"SPEED" INTEGER NOT NULL,"OAT" INTEGER NOT NULL);

# --- !Downs

drop table "WINDS";
drop table "PLACES";
drop table "JOURNEY_LEGS";
drop table "JOURNEYS";

